import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#dae2fd",
        "primary-container": "#6063ee",
        "surface-tint": "#494bd6",
        "surface-container": "#efecf8",
        "primary-fixed": "#e1e0ff",
        primary: "#4648d4",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#07006c",
        "on-background": "#1b1b23",
        "on-primary-container": "#fffbff",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        tertiary: "#904900",
        "tertiary-fixed": "#ffdcc5",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "inverse-on-surface": "#f2effb",
        "primary-fixed-dim": "#c0c1ff",
        "surface-bright": "#fcf8ff",
        "inverse-primary": "#c0c1ff",
        outline: "#767586",
        "surface-variant": "#e4e1ed",
        "on-secondary-fixed": "#131b2e",
        surface: "#fcf8ff",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#dae2fd",
        "surface-container-highest": "#e4e1ed",
        "surface-container-low": "#f5f2fe",
        "on-surface": "#1b1b23",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary-container": "#5c647a",
        "surface-container-high": "#e9e6f3",
        "tertiary-container": "#b55d00",
        "secondary-fixed-dim": "#bec6e0",
        "outline-variant": "#c7c4d7",
        "surface-dim": "#dbd8e4",
        secondary: "#565e74",
        "on-surface-variant": "#464554",
        background: "#fcf8ff",
        "inverse-surface": "#303038",
        "tertiary-fixed-dim": "#ffb783",
        navy: "#0f172a",
      },
      spacing: {
        "sidebar-width": "280px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "24px",
        base: "4px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "h3": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
        "h1": ["30px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "1", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "h2": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
      },
      animation: {
        "slide-in": "slideIn 0.2s ease-out",
        "fade-in": "fadeIn 0.2s ease-out",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        slideIn: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
